// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "high-go-press/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 热门计数器请求
type TopCountersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CounterType   string                    `protobuf:"bytes,1,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	Limit         int32                     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeRange     string                    `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // 时间范围: "1h", "24h", "7d", "30d"
	Pagination    *common.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopCountersRequest) Reset() {
	*x = TopCountersRequest{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopCountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCountersRequest) ProtoMessage() {}

func (x *TopCountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCountersRequest.ProtoReflect.Descriptor instead.
func (*TopCountersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TopCountersRequest) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *TopCountersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TopCountersRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *TopCountersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 计数器条目
type CounterItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceId     string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType    string                 `protobuf:"bytes,2,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	Value          int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	IncrementCount int64                  `protobuf:"varint,4,opt,name=increment_count,json=incrementCount,proto3" json:"increment_count,omitempty"`
	LastUpdated    *common.Timestamp      `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CounterItem) Reset() {
	*x = CounterItem{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterItem) ProtoMessage() {}

func (x *CounterItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterItem.ProtoReflect.Descriptor instead.
func (*CounterItem) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CounterItem) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CounterItem) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *CounterItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CounterItem) GetIncrementCount() int64 {
	if x != nil {
		return x.IncrementCount
	}
	return 0
}

func (x *CounterItem) GetLastUpdated() *common.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// 热门计数器响应
type TopCountersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        *common.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Counters      []*CounterItem             `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopCountersResponse) Reset() {
	*x = TopCountersResponse{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopCountersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCountersResponse) ProtoMessage() {}

func (x *TopCountersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCountersResponse.ProtoReflect.Descriptor instead.
func (*TopCountersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TopCountersResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TopCountersResponse) GetCounters() []*CounterItem {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *TopCountersResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 统计请求
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,2,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	TimeRange     string                 `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Metrics       []string               `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"` // 要查询的指标: "total", "avg", "peak", "trend"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *StatsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *StatsRequest) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *StatsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *StatsRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 统计响应
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,3,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 指标名 -> 值
	TimeSeries    []*TimeSeriesPoint     `protobuf:"bytes,5,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *StatsResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatsResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *StatsResponse) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *StatsResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *StatsResponse) GetTimeSeries() []*TimeSeriesPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

// 时间序列数据点
type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *common.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSeriesPoint) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 系统监控请求
type SystemMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Components    []string               `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"` // "worker_pool", "object_pool", "kafka", "redis"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetricsRequest) Reset() {
	*x = SystemMetricsRequest{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsRequest) ProtoMessage() {}

func (x *SystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*SystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *SystemMetricsRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

// 系统监控响应
type SystemMetricsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        *common.Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       map[string]*ComponentMetrics `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetricsResponse) Reset() {
	*x = SystemMetricsResponse{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsResponse) ProtoMessage() {}

func (x *SystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*SystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *SystemMetricsResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SystemMetricsResponse) GetMetrics() map[string]*ComponentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 组件指标
type ComponentMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Values        map[string]float64     `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	CollectedAt   *common.Timestamp      `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentMetrics) Reset() {
	*x = ComponentMetrics{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMetrics) ProtoMessage() {}

func (x *ComponentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMetrics.ProtoReflect.Descriptor instead.
func (*ComponentMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentMetrics) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ComponentMetrics) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ComponentMetrics) GetCollectedAt() *common.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_api_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"#api/proto/analytics/analytics.proto\x12\tanalytics\x1a\x1capi/proto/common/types.proto\"\xa7\x01\n" +
	"\x12TopCountersRequest\x12!\n" +
	"\fcounter_type\x18\x01 \x01(\tR\vcounterType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"time_range\x18\x03 \x01(\tR\ttimeRange\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xc6\x01\n" +
	"\vCounterItem\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x02 \x01(\tR\vcounterType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12'\n" +
	"\x0fincrement_count\x18\x04 \x01(\x03R\x0eincrementCount\x124\n" +
	"\flast_updated\x18\x05 \x01(\v2\x11.common.TimestampR\vlastUpdated\"\xad\x01\n" +
	"\x13TopCountersResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x122\n" +
	"\bcounters\x18\x02 \x03(\v2\x16.analytics.CounterItemR\bcounters\x12:\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"\x8b\x01\n" +
	"\fStatsRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x02 \x01(\tR\vcounterType\x12\x1d\n" +
	"\n" +
	"time_range\x18\x03 \x01(\tR\ttimeRange\x12\x18\n" +
	"\ametrics\x18\x04 \x03(\tR\ametrics\"\xb5\x02\n" +
	"\rStatsResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x03 \x01(\tR\vcounterType\x12?\n" +
	"\ametrics\x18\x04 \x03(\v2%.analytics.StatsResponse.MetricsEntryR\ametrics\x12;\n" +
	"\vtime_series\x18\x05 \x03(\v2\x1a.analytics.TimeSeriesPointR\n" +
	"timeSeries\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"X\n" +
	"\x0fTimeSeriesPoint\x12/\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x11.common.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"6\n" +
	"\x14SystemMetricsRequest\x12\x1e\n" +
	"\n" +
	"components\x18\x01 \x03(\tR\n" +
	"components\"\xe1\x01\n" +
	"\x15SystemMetricsResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12G\n" +
	"\ametrics\x18\x02 \x03(\v2-.analytics.SystemMetricsResponse.MetricsEntryR\ametrics\x1aW\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.analytics.ComponentMetricsR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x10ComponentMetrics\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12?\n" +
	"\x06values\x18\x02 \x03(\v2'.analytics.ComponentMetrics.ValuesEntryR\x06values\x124\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x11.common.TimestampR\vcollectedAt\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xda\x01\n" +
	"\x13HealthCheckResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12E\n" +
	"\adetails\x18\x03 \x03(\v2+.analytics.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xce\x02\n" +
	"\x10AnalyticsService\x12O\n" +
	"\x0eGetTopCounters\x12\x1d.analytics.TopCountersRequest\x1a\x1e.analytics.TopCountersResponse\x12D\n" +
	"\x0fGetCounterStats\x12\x17.analytics.StatsRequest\x1a\x18.analytics.StatsResponse\x12U\n" +
	"\x10GetSystemMetrics\x12\x1f.analytics.SystemMetricsRequest\x1a .analytics.SystemMetricsResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.analytics.HealthCheckRequest\x1a\x1e.analytics.HealthCheckResponseB#Z!high-go-press/api/proto/analyticsb\x06proto3"

var (
	file_api_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_api_proto_analytics_analytics_proto_rawDescData []byte
)

func file_api_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_api_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_api_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analytics_analytics_proto_rawDesc), len(file_api_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_api_proto_analytics_analytics_proto_rawDescData
}

var file_api_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_analytics_analytics_proto_goTypes = []any{
	(*TopCountersRequest)(nil),        // 0: analytics.TopCountersRequest
	(*CounterItem)(nil),               // 1: analytics.CounterItem
	(*TopCountersResponse)(nil),       // 2: analytics.TopCountersResponse
	(*StatsRequest)(nil),              // 3: analytics.StatsRequest
	(*StatsResponse)(nil),             // 4: analytics.StatsResponse
	(*TimeSeriesPoint)(nil),           // 5: analytics.TimeSeriesPoint
	(*SystemMetricsRequest)(nil),      // 6: analytics.SystemMetricsRequest
	(*SystemMetricsResponse)(nil),     // 7: analytics.SystemMetricsResponse
	(*ComponentMetrics)(nil),          // 8: analytics.ComponentMetrics
	(*HealthCheckRequest)(nil),        // 9: analytics.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 10: analytics.HealthCheckResponse
	nil,                               // 11: analytics.StatsResponse.MetricsEntry
	nil,                               // 12: analytics.SystemMetricsResponse.MetricsEntry
	nil,                               // 13: analytics.ComponentMetrics.ValuesEntry
	nil,                               // 14: analytics.HealthCheckResponse.DetailsEntry
	(*common.PaginationRequest)(nil),  // 15: common.PaginationRequest
	(*common.Timestamp)(nil),          // 16: common.Timestamp
	(*common.Status)(nil),             // 17: common.Status
	(*common.PaginationResponse)(nil), // 18: common.PaginationResponse
}
var file_api_proto_analytics_analytics_proto_depIdxs = []int32{
	15, // 0: analytics.TopCountersRequest.pagination:type_name -> common.PaginationRequest
	16, // 1: analytics.CounterItem.last_updated:type_name -> common.Timestamp
	17, // 2: analytics.TopCountersResponse.status:type_name -> common.Status
	1,  // 3: analytics.TopCountersResponse.counters:type_name -> analytics.CounterItem
	18, // 4: analytics.TopCountersResponse.pagination:type_name -> common.PaginationResponse
	17, // 5: analytics.StatsResponse.status:type_name -> common.Status
	11, // 6: analytics.StatsResponse.metrics:type_name -> analytics.StatsResponse.MetricsEntry
	5,  // 7: analytics.StatsResponse.time_series:type_name -> analytics.TimeSeriesPoint
	16, // 8: analytics.TimeSeriesPoint.timestamp:type_name -> common.Timestamp
	17, // 9: analytics.SystemMetricsResponse.status:type_name -> common.Status
	12, // 10: analytics.SystemMetricsResponse.metrics:type_name -> analytics.SystemMetricsResponse.MetricsEntry
	13, // 11: analytics.ComponentMetrics.values:type_name -> analytics.ComponentMetrics.ValuesEntry
	16, // 12: analytics.ComponentMetrics.collected_at:type_name -> common.Timestamp
	17, // 13: analytics.HealthCheckResponse.status:type_name -> common.Status
	14, // 14: analytics.HealthCheckResponse.details:type_name -> analytics.HealthCheckResponse.DetailsEntry
	8,  // 15: analytics.SystemMetricsResponse.MetricsEntry.value:type_name -> analytics.ComponentMetrics
	0,  // 16: analytics.AnalyticsService.GetTopCounters:input_type -> analytics.TopCountersRequest
	3,  // 17: analytics.AnalyticsService.GetCounterStats:input_type -> analytics.StatsRequest
	6,  // 18: analytics.AnalyticsService.GetSystemMetrics:input_type -> analytics.SystemMetricsRequest
	9,  // 19: analytics.AnalyticsService.HealthCheck:input_type -> analytics.HealthCheckRequest
	2,  // 20: analytics.AnalyticsService.GetTopCounters:output_type -> analytics.TopCountersResponse
	4,  // 21: analytics.AnalyticsService.GetCounterStats:output_type -> analytics.StatsResponse
	7,  // 22: analytics.AnalyticsService.GetSystemMetrics:output_type -> analytics.SystemMetricsResponse
	10, // 23: analytics.AnalyticsService.HealthCheck:output_type -> analytics.HealthCheckResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_analytics_proto_init() }
func file_api_proto_analytics_analytics_proto_init() {
	if File_api_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_analytics_proto_rawDesc), len(file_api_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_api_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_api_proto_analytics_analytics_proto = out.File
	file_api_proto_analytics_analytics_proto_goTypes = nil
	file_api_proto_analytics_analytics_proto_depIdxs = nil
}
