// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/counter/counter.proto

package counter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "high-go-press/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 增量请求
type IncrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,2,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{0}
}

func (x *IncrementRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *IncrementRequest) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *IncrementRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *IncrementRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 增量响应
type IncrementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentValue  int64                  `protobuf:"varint,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,4,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementResponse) Reset() {
	*x = IncrementResponse{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementResponse) ProtoMessage() {}

func (x *IncrementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementResponse.ProtoReflect.Descriptor instead.
func (*IncrementResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{1}
}

func (x *IncrementResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *IncrementResponse) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *IncrementResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *IncrementResponse) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

// 获取计数器请求
type GetCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,2,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCounterRequest) Reset() {
	*x = GetCounterRequest{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCounterRequest) ProtoMessage() {}

func (x *GetCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCounterRequest.ProtoReflect.Descriptor instead.
func (*GetCounterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{2}
}

func (x *GetCounterRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetCounterRequest) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

// 获取计数器响应
type GetCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CounterType   string                 `protobuf:"bytes,4,opt,name=counter_type,json=counterType,proto3" json:"counter_type,omitempty"`
	LastUpdated   *common.Timestamp      `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCounterResponse) Reset() {
	*x = GetCounterResponse{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCounterResponse) ProtoMessage() {}

func (x *GetCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCounterResponse.ProtoReflect.Descriptor instead.
func (*GetCounterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{3}
}

func (x *GetCounterResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetCounterResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetCounterResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetCounterResponse) GetCounterType() string {
	if x != nil {
		return x.CounterType
	}
	return ""
}

func (x *GetCounterResponse) GetLastUpdated() *common.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// 批量获取请求
type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetCounterRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetRequest) GetRequests() []*GetCounterRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// 批量获取响应
type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Counters      []*GetCounterResponse  `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BatchGetResponse) GetCounters() []*GetCounterResponse {
	if x != nil {
		return x.Counters
	}
	return nil
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_counter_counter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_counter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_counter_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_proto_counter_counter_proto protoreflect.FileDescriptor

const file_api_proto_counter_counter_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/counter/counter.proto\x12\acounter\x1a\x1capi/proto/common/types.proto\"\xee\x01\n" +
	"\x10IncrementRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x02 \x01(\tR\vcounterType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.counter.IncrementRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x11IncrementResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x03R\fcurrentValue\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x04 \x01(\tR\vcounterType\"W\n" +
	"\x11GetCounterRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x02 \x01(\tR\vcounterType\"\xcc\x01\n" +
	"\x12GetCounterResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcounter_type\x18\x04 \x01(\tR\vcounterType\x124\n" +
	"\flast_updated\x18\x05 \x01(\v2\x11.common.TimestampR\vlastUpdated\"I\n" +
	"\x0fBatchGetRequest\x126\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.counter.GetCounterRequestR\brequests\"s\n" +
	"\x10BatchGetResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x127\n" +
	"\bcounters\x18\x02 \x03(\v2\x1b.counter.GetCounterResponseR\bcounters\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xd8\x01\n" +
	"\x13HealthCheckResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12C\n" +
	"\adetails\x18\x03 \x03(\v2).counter.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb5\x02\n" +
	"\x0eCounterService\x12I\n" +
	"\x10IncrementCounter\x12\x19.counter.IncrementRequest\x1a\x1a.counter.IncrementResponse\x12E\n" +
	"\n" +
	"GetCounter\x12\x1a.counter.GetCounterRequest\x1a\x1b.counter.GetCounterResponse\x12G\n" +
	"\x10BatchGetCounters\x12\x18.counter.BatchGetRequest\x1a\x19.counter.BatchGetResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.counter.HealthCheckRequest\x1a\x1c.counter.HealthCheckResponseB!Z\x1fhigh-go-press/api/proto/counterb\x06proto3"

var (
	file_api_proto_counter_counter_proto_rawDescOnce sync.Once
	file_api_proto_counter_counter_proto_rawDescData []byte
)

func file_api_proto_counter_counter_proto_rawDescGZIP() []byte {
	file_api_proto_counter_counter_proto_rawDescOnce.Do(func() {
		file_api_proto_counter_counter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_counter_counter_proto_rawDesc), len(file_api_proto_counter_counter_proto_rawDesc)))
	})
	return file_api_proto_counter_counter_proto_rawDescData
}

var file_api_proto_counter_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_counter_counter_proto_goTypes = []any{
	(*IncrementRequest)(nil),    // 0: counter.IncrementRequest
	(*IncrementResponse)(nil),   // 1: counter.IncrementResponse
	(*GetCounterRequest)(nil),   // 2: counter.GetCounterRequest
	(*GetCounterResponse)(nil),  // 3: counter.GetCounterResponse
	(*BatchGetRequest)(nil),     // 4: counter.BatchGetRequest
	(*BatchGetResponse)(nil),    // 5: counter.BatchGetResponse
	(*HealthCheckRequest)(nil),  // 6: counter.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: counter.HealthCheckResponse
	nil,                         // 8: counter.IncrementRequest.MetadataEntry
	nil,                         // 9: counter.HealthCheckResponse.DetailsEntry
	(*common.Status)(nil),       // 10: common.Status
	(*common.Timestamp)(nil),    // 11: common.Timestamp
}
var file_api_proto_counter_counter_proto_depIdxs = []int32{
	8,  // 0: counter.IncrementRequest.metadata:type_name -> counter.IncrementRequest.MetadataEntry
	10, // 1: counter.IncrementResponse.status:type_name -> common.Status
	10, // 2: counter.GetCounterResponse.status:type_name -> common.Status
	11, // 3: counter.GetCounterResponse.last_updated:type_name -> common.Timestamp
	2,  // 4: counter.BatchGetRequest.requests:type_name -> counter.GetCounterRequest
	10, // 5: counter.BatchGetResponse.status:type_name -> common.Status
	3,  // 6: counter.BatchGetResponse.counters:type_name -> counter.GetCounterResponse
	10, // 7: counter.HealthCheckResponse.status:type_name -> common.Status
	9,  // 8: counter.HealthCheckResponse.details:type_name -> counter.HealthCheckResponse.DetailsEntry
	0,  // 9: counter.CounterService.IncrementCounter:input_type -> counter.IncrementRequest
	2,  // 10: counter.CounterService.GetCounter:input_type -> counter.GetCounterRequest
	4,  // 11: counter.CounterService.BatchGetCounters:input_type -> counter.BatchGetRequest
	6,  // 12: counter.CounterService.HealthCheck:input_type -> counter.HealthCheckRequest
	1,  // 13: counter.CounterService.IncrementCounter:output_type -> counter.IncrementResponse
	3,  // 14: counter.CounterService.GetCounter:output_type -> counter.GetCounterResponse
	5,  // 15: counter.CounterService.BatchGetCounters:output_type -> counter.BatchGetResponse
	7,  // 16: counter.CounterService.HealthCheck:output_type -> counter.HealthCheckResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_counter_counter_proto_init() }
func file_api_proto_counter_counter_proto_init() {
	if File_api_proto_counter_counter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_counter_counter_proto_rawDesc), len(file_api_proto_counter_counter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_counter_counter_proto_goTypes,
		DependencyIndexes: file_api_proto_counter_counter_proto_depIdxs,
		MessageInfos:      file_api_proto_counter_counter_proto_msgTypes,
	}.Build()
	File_api_proto_counter_counter_proto = out.File
	file_api_proto_counter_counter_proto_goTypes = nil
	file_api_proto_counter_counter_proto_depIdxs = nil
}
