# HighGoPress 微服务配置
# Phase 2 Day 1

# 服务发现配置
discovery:
  type: "consul"
  consul:
    address: "localhost:8500"
    scheme: "http"
    timeout: "10s"

# Gateway 网关配置
gateway:
server:
  host: "0.0.0.0"
  port: 8080
    mode: "release" # debug, release, test
  timeout:
    read: "30s"
    write: "30s"
    idle: "120s"
  cors:
    enabled: true
    origins: ["*"]

# Counter 计数服务配置
counter:
  server:
    host: "0.0.0.0"
    port: 9001
  grpc:
    max_recv_msg_size: "4MB"
    max_send_msg_size: "4MB"
    max_connections: 1000
    keep_alive:
      time: "60s"
      timeout: "10s"
  performance:
    worker_pool_size: 1000
    object_pool_enabled: true
    batch_size: 100

# Analytics 分析服务配置  
analytics:
  server:
    host: "0.0.0.0"
    port: 9002
  grpc:
    max_recv_msg_size: "4MB"
    max_send_msg_size: "4MB"
    max_connections: 500
    keep_alive:
      time: "60s"
      timeout: "10s"

# Redis 配置
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

# Kafka 配置
kafka:
  brokers: ["localhost:9092"]
  topic: "counter_events"
  producer:
    batch_size: 16384
    linger_ms: 10
    buffer_memory: 33554432
  consumer:
    group_id: "high_go_press_analytics"
    auto_offset_reset: "earliest"

# 日志配置
logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, console
  output: "stdout" # stdout, file
  file:
    path: "/var/log/high-go-press"
    max_size: 100 # MB
    max_age: 7 # days
    max_backups: 10

# 监控配置
monitoring:
  pprof:
    enabled: true
    port: 6060
  prometheus:
    enabled: true
    port: 2112
    path: "/metrics"
  health_check:
    port: 8090
    path: "/health" 