# Production环境特定配置
environment: "prod"

gateway:
  server:
    host: "0.0.0.0"
    port: 8080
    mode: "release"

counter:
  server:
    port: 9001
  performance:
    worker_pool_size: 2000

analytics:
  server:
    port: 9002

redis:
  address: "redis-cluster:6379"
  pool_size: 50

kafka:
  mode: "real"
  brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  topic: "counter-events-prod"

log:
  level: "warn"
  format: "json"
  output: "file"
  file:
    path: "/var/log/high-go-press"
