# Test环境特定配置
environment: "test"

gateway:
  server:
    host: "0.0.0.0"
    port: 8081
    mode: "test"

counter:
  server:
    port: 9011
  performance:
    worker_pool_size: 500

analytics:
  server:
    port: 9012

redis:
  address: "localhost:6380"
  db: 1

kafka:
  mode: "mock"
  topic: "counter-events-test"

log:
  level: "debug"
